//go:build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/const.go", nil, 0)
	if err != nil {
		return err
	}

	var names []string
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			for _, ident := range vs.Names {
				if strings.HasPrefix(ident.Name, "DLT_") {
					names = append(names, ident.Name)
				}
			}
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by dlt; DO NOT EDIT.\n\n")
	b.WriteString("package pcapfilter\n\n")
	b.WriteString("import (\n")
	for _, imp := range []string{
		"fmt",
		"strconv",
		"strings",
		"",
		"github.com/pgaskin/go-pcapfilter/internal",
	} {
		if imp == "" {
			fmt.Fprint(&b, "\n")
		} else {
			fmt.Fprintf(&b, "%q\n", imp)
		}
	}
	b.WriteString(")\n")
	b.WriteString("const (\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%s = LinkType(bpf_wasm.%s)\n", name, name)
	}
	b.WriteString(")\n\n")

	b.WriteString(`// UnmarshalText parses a link-layer type by name (e.g. "EN10MB" or "DLT_EN10MB") or integer.` + "\n")
	b.WriteString(`func (t *LinkType) UnmarshalText(buf []byte) error {` + "\n")
	b.WriteString(`switch strings.TrimPrefix(strings.ToUpper(string(buf)), "DLT_") {` + "\n")
	for _, name := range names {
		fmt.Fprintf(&b, "case %q:\n", strings.ToUpper(strings.TrimPrefix(name, "DLT_")))
		fmt.Fprintf(&b, "*t = %s\n", name)
		b.WriteString(`return nil` + "\n")
	}
	b.WriteString(`default:` + "\n")
	b.WriteString(`if n, err := strconv.ParseInt(string(buf), 0, 0); err == nil {` + "\n")
	b.WriteString(`*t = LinkType(n)` + "\n")
	b.WriteString(`return nil` + "\n")
	b.WriteString(`}` + "\n")
	b.WriteString(`return fmt.Errorf("invalid link type %q", buf)` + "\n")
	b.WriteString(`}` + "\n")
	b.WriteString(`}` + "\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile("dlt_generated.go", out, 0644)
}
