//go:build ignore

package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, "internal/const.go", nil, 0)
	if err != nil {
		return err
	}

	var b strings.Builder
	b.WriteString("// Code generated by dlt; DO NOT EDIT.\n\n")
	b.WriteString("package pcapfilter\n\n")
	fmt.Fprintf(&b, "import bpf_wasm %q\n", "github.com/pgaskin/go-pcapfilter/internal")
	b.WriteString("const (\n")
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			for _, ident := range vs.Names {
				if strings.HasPrefix(ident.Name, "DLT_") {
					fmt.Fprintf(&b, "%s = LinkType(bpf_wasm.%s)\n", ident.Name, ident.Name)
				}
			}
		}
	}
	b.WriteString(")\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("format: %w", err)
	}
	return os.WriteFile("dlt_generated.go", out, 0644)
}
