// Code generated by dlt; DO NOT EDIT.

package pcapfilter

import (
	"strings"

	"github.com/pgaskin/go-pcapfilter/internal"
)

const (
	DLT_NULL                       = LinkType(bpf_wasm.DLT_NULL)
	DLT_EN10MB                     = LinkType(bpf_wasm.DLT_EN10MB)
	DLT_EN3MB                      = LinkType(bpf_wasm.DLT_EN3MB)
	DLT_AX25                       = LinkType(bpf_wasm.DLT_AX25)
	DLT_PRONET                     = LinkType(bpf_wasm.DLT_PRONET)
	DLT_CHAOS                      = LinkType(bpf_wasm.DLT_CHAOS)
	DLT_IEEE802                    = LinkType(bpf_wasm.DLT_IEEE802)
	DLT_ARCNET                     = LinkType(bpf_wasm.DLT_ARCNET)
	DLT_SLIP                       = LinkType(bpf_wasm.DLT_SLIP)
	DLT_PPP                        = LinkType(bpf_wasm.DLT_PPP)
	DLT_FDDI                       = LinkType(bpf_wasm.DLT_FDDI)
	DLT_ATM_RFC1483                = LinkType(bpf_wasm.DLT_ATM_RFC1483)
	DLT_RAW                        = LinkType(bpf_wasm.DLT_RAW)
	DLT_SLIP_BSDOS                 = LinkType(bpf_wasm.DLT_SLIP_BSDOS)
	DLT_PPP_BSDOS                  = LinkType(bpf_wasm.DLT_PPP_BSDOS)
	DLT_ATM_CLIP                   = LinkType(bpf_wasm.DLT_ATM_CLIP)
	DLT_REDBACK_SMARTEDGE          = LinkType(bpf_wasm.DLT_REDBACK_SMARTEDGE)
	DLT_PPP_SERIAL                 = LinkType(bpf_wasm.DLT_PPP_SERIAL)
	DLT_PPP_ETHER                  = LinkType(bpf_wasm.DLT_PPP_ETHER)
	DLT_SYMANTEC_FIREWALL          = LinkType(bpf_wasm.DLT_SYMANTEC_FIREWALL)
	DLT_C_HDLC                     = LinkType(bpf_wasm.DLT_C_HDLC)
	DLT_IEEE802_11                 = LinkType(bpf_wasm.DLT_IEEE802_11)
	DLT_FRELAY                     = LinkType(bpf_wasm.DLT_FRELAY)
	DLT_LOOP                       = LinkType(bpf_wasm.DLT_LOOP)
	DLT_ENC                        = LinkType(bpf_wasm.DLT_ENC)
	DLT_HDLC                       = LinkType(bpf_wasm.DLT_HDLC)
	DLT_LINUX_SLL                  = LinkType(bpf_wasm.DLT_LINUX_SLL)
	DLT_LTALK                      = LinkType(bpf_wasm.DLT_LTALK)
	DLT_ECONET                     = LinkType(bpf_wasm.DLT_ECONET)
	DLT_IPFILTER                   = LinkType(bpf_wasm.DLT_IPFILTER)
	DLT_PFLOG                      = LinkType(bpf_wasm.DLT_PFLOG)
	DLT_CISCO_IOS                  = LinkType(bpf_wasm.DLT_CISCO_IOS)
	DLT_PRISM_HEADER               = LinkType(bpf_wasm.DLT_PRISM_HEADER)
	DLT_AIRONET_HEADER             = LinkType(bpf_wasm.DLT_AIRONET_HEADER)
	DLT_HHDLC                      = LinkType(bpf_wasm.DLT_HHDLC)
	DLT_IP_OVER_FC                 = LinkType(bpf_wasm.DLT_IP_OVER_FC)
	DLT_SUNATM                     = LinkType(bpf_wasm.DLT_SUNATM)
	DLT_RIO                        = LinkType(bpf_wasm.DLT_RIO)
	DLT_PCI_EXP                    = LinkType(bpf_wasm.DLT_PCI_EXP)
	DLT_AURORA                     = LinkType(bpf_wasm.DLT_AURORA)
	DLT_IEEE802_11_RADIO           = LinkType(bpf_wasm.DLT_IEEE802_11_RADIO)
	DLT_TZSP                       = LinkType(bpf_wasm.DLT_TZSP)
	DLT_ARCNET_LINUX               = LinkType(bpf_wasm.DLT_ARCNET_LINUX)
	DLT_JUNIPER_MLPPP              = LinkType(bpf_wasm.DLT_JUNIPER_MLPPP)
	DLT_JUNIPER_MLFR               = LinkType(bpf_wasm.DLT_JUNIPER_MLFR)
	DLT_JUNIPER_ES                 = LinkType(bpf_wasm.DLT_JUNIPER_ES)
	DLT_JUNIPER_GGSN               = LinkType(bpf_wasm.DLT_JUNIPER_GGSN)
	DLT_JUNIPER_MFR                = LinkType(bpf_wasm.DLT_JUNIPER_MFR)
	DLT_JUNIPER_ATM2               = LinkType(bpf_wasm.DLT_JUNIPER_ATM2)
	DLT_JUNIPER_SERVICES           = LinkType(bpf_wasm.DLT_JUNIPER_SERVICES)
	DLT_JUNIPER_ATM1               = LinkType(bpf_wasm.DLT_JUNIPER_ATM1)
	DLT_APPLE_IP_OVER_IEEE1394     = LinkType(bpf_wasm.DLT_APPLE_IP_OVER_IEEE1394)
	DLT_MTP2_WITH_PHDR             = LinkType(bpf_wasm.DLT_MTP2_WITH_PHDR)
	DLT_MTP2                       = LinkType(bpf_wasm.DLT_MTP2)
	DLT_MTP3                       = LinkType(bpf_wasm.DLT_MTP3)
	DLT_SCCP                       = LinkType(bpf_wasm.DLT_SCCP)
	DLT_DOCSIS                     = LinkType(bpf_wasm.DLT_DOCSIS)
	DLT_LINUX_IRDA                 = LinkType(bpf_wasm.DLT_LINUX_IRDA)
	DLT_IBM_SP                     = LinkType(bpf_wasm.DLT_IBM_SP)
	DLT_IBM_SN                     = LinkType(bpf_wasm.DLT_IBM_SN)
	DLT_USER0                      = LinkType(bpf_wasm.DLT_USER0)
	DLT_USER1                      = LinkType(bpf_wasm.DLT_USER1)
	DLT_USER2                      = LinkType(bpf_wasm.DLT_USER2)
	DLT_USER3                      = LinkType(bpf_wasm.DLT_USER3)
	DLT_USER4                      = LinkType(bpf_wasm.DLT_USER4)
	DLT_USER5                      = LinkType(bpf_wasm.DLT_USER5)
	DLT_USER6                      = LinkType(bpf_wasm.DLT_USER6)
	DLT_USER7                      = LinkType(bpf_wasm.DLT_USER7)
	DLT_USER8                      = LinkType(bpf_wasm.DLT_USER8)
	DLT_USER9                      = LinkType(bpf_wasm.DLT_USER9)
	DLT_USER10                     = LinkType(bpf_wasm.DLT_USER10)
	DLT_USER11                     = LinkType(bpf_wasm.DLT_USER11)
	DLT_USER12                     = LinkType(bpf_wasm.DLT_USER12)
	DLT_USER13                     = LinkType(bpf_wasm.DLT_USER13)
	DLT_USER14                     = LinkType(bpf_wasm.DLT_USER14)
	DLT_USER15                     = LinkType(bpf_wasm.DLT_USER15)
	DLT_IEEE802_11_RADIO_AVS       = LinkType(bpf_wasm.DLT_IEEE802_11_RADIO_AVS)
	DLT_JUNIPER_MONITOR            = LinkType(bpf_wasm.DLT_JUNIPER_MONITOR)
	DLT_BACNET_MS_TP               = LinkType(bpf_wasm.DLT_BACNET_MS_TP)
	DLT_PPP_PPPD                   = LinkType(bpf_wasm.DLT_PPP_PPPD)
	DLT_JUNIPER_PPPOE              = LinkType(bpf_wasm.DLT_JUNIPER_PPPOE)
	DLT_JUNIPER_PPPOE_ATM          = LinkType(bpf_wasm.DLT_JUNIPER_PPPOE_ATM)
	DLT_GPRS_LLC                   = LinkType(bpf_wasm.DLT_GPRS_LLC)
	DLT_GPF_T                      = LinkType(bpf_wasm.DLT_GPF_T)
	DLT_GPF_F                      = LinkType(bpf_wasm.DLT_GPF_F)
	DLT_GCOM_T1E1                  = LinkType(bpf_wasm.DLT_GCOM_T1E1)
	DLT_GCOM_SERIAL                = LinkType(bpf_wasm.DLT_GCOM_SERIAL)
	DLT_JUNIPER_PIC_PEER           = LinkType(bpf_wasm.DLT_JUNIPER_PIC_PEER)
	DLT_ERF_ETH                    = LinkType(bpf_wasm.DLT_ERF_ETH)
	DLT_ERF_POS                    = LinkType(bpf_wasm.DLT_ERF_POS)
	DLT_LINUX_LAPD                 = LinkType(bpf_wasm.DLT_LINUX_LAPD)
	DLT_JUNIPER_ETHER              = LinkType(bpf_wasm.DLT_JUNIPER_ETHER)
	DLT_JUNIPER_PPP                = LinkType(bpf_wasm.DLT_JUNIPER_PPP)
	DLT_JUNIPER_FRELAY             = LinkType(bpf_wasm.DLT_JUNIPER_FRELAY)
	DLT_JUNIPER_CHDLC              = LinkType(bpf_wasm.DLT_JUNIPER_CHDLC)
	DLT_MFR                        = LinkType(bpf_wasm.DLT_MFR)
	DLT_JUNIPER_VP                 = LinkType(bpf_wasm.DLT_JUNIPER_VP)
	DLT_A429                       = LinkType(bpf_wasm.DLT_A429)
	DLT_A653_ICM                   = LinkType(bpf_wasm.DLT_A653_ICM)
	DLT_USB                        = LinkType(bpf_wasm.DLT_USB)
	DLT_USB_FREEBSD                = LinkType(bpf_wasm.DLT_USB_FREEBSD)
	DLT_BLUETOOTH_HCI_H4           = LinkType(bpf_wasm.DLT_BLUETOOTH_HCI_H4)
	DLT_IEEE802_16_MAC_CPS         = LinkType(bpf_wasm.DLT_IEEE802_16_MAC_CPS)
	DLT_USB_LINUX                  = LinkType(bpf_wasm.DLT_USB_LINUX)
	DLT_CAN20B                     = LinkType(bpf_wasm.DLT_CAN20B)
	DLT_IEEE802_15_4_LINUX         = LinkType(bpf_wasm.DLT_IEEE802_15_4_LINUX)
	DLT_PPI                        = LinkType(bpf_wasm.DLT_PPI)
	DLT_IEEE802_16_MAC_CPS_RADIO   = LinkType(bpf_wasm.DLT_IEEE802_16_MAC_CPS_RADIO)
	DLT_JUNIPER_ISM                = LinkType(bpf_wasm.DLT_JUNIPER_ISM)
	DLT_IEEE802_15_4_WITHFCS       = LinkType(bpf_wasm.DLT_IEEE802_15_4_WITHFCS)
	DLT_SITA                       = LinkType(bpf_wasm.DLT_SITA)
	DLT_ERF                        = LinkType(bpf_wasm.DLT_ERF)
	DLT_RAIF1                      = LinkType(bpf_wasm.DLT_RAIF1)
	DLT_IPMB_KONTRON               = LinkType(bpf_wasm.DLT_IPMB_KONTRON)
	DLT_JUNIPER_ST                 = LinkType(bpf_wasm.DLT_JUNIPER_ST)
	DLT_BLUETOOTH_HCI_H4_WITH_PHDR = LinkType(bpf_wasm.DLT_BLUETOOTH_HCI_H4_WITH_PHDR)
	DLT_AX25_KISS                  = LinkType(bpf_wasm.DLT_AX25_KISS)
	DLT_LAPD                       = LinkType(bpf_wasm.DLT_LAPD)
	DLT_PPP_WITH_DIR               = LinkType(bpf_wasm.DLT_PPP_WITH_DIR)
	DLT_C_HDLC_WITH_DIR            = LinkType(bpf_wasm.DLT_C_HDLC_WITH_DIR)
	DLT_FRELAY_WITH_DIR            = LinkType(bpf_wasm.DLT_FRELAY_WITH_DIR)
	DLT_LAPB_WITH_DIR              = LinkType(bpf_wasm.DLT_LAPB_WITH_DIR)
	DLT_I2C_LINUX                  = LinkType(bpf_wasm.DLT_I2C_LINUX)
	DLT_IPMB_LINUX                 = LinkType(bpf_wasm.DLT_IPMB_LINUX)
	DLT_FLEXRAY                    = LinkType(bpf_wasm.DLT_FLEXRAY)
	DLT_MOST                       = LinkType(bpf_wasm.DLT_MOST)
	DLT_LIN                        = LinkType(bpf_wasm.DLT_LIN)
	DLT_X2E_SERIAL                 = LinkType(bpf_wasm.DLT_X2E_SERIAL)
	DLT_X2E_XORAYA                 = LinkType(bpf_wasm.DLT_X2E_XORAYA)
	DLT_IEEE802_15_4_NONASK_PHY    = LinkType(bpf_wasm.DLT_IEEE802_15_4_NONASK_PHY)
	DLT_LINUX_EVDEV                = LinkType(bpf_wasm.DLT_LINUX_EVDEV)
	DLT_GSMTAP_UM                  = LinkType(bpf_wasm.DLT_GSMTAP_UM)
	DLT_GSMTAP_ABIS                = LinkType(bpf_wasm.DLT_GSMTAP_ABIS)
	DLT_MPLS                       = LinkType(bpf_wasm.DLT_MPLS)
	DLT_USB_LINUX_MMAPPED          = LinkType(bpf_wasm.DLT_USB_LINUX_MMAPPED)
	DLT_DECT                       = LinkType(bpf_wasm.DLT_DECT)
	DLT_AOS                        = LinkType(bpf_wasm.DLT_AOS)
	DLT_WIHART                     = LinkType(bpf_wasm.DLT_WIHART)
	DLT_FC_2                       = LinkType(bpf_wasm.DLT_FC_2)
	DLT_FC_2_WITH_FRAME_DELIMS     = LinkType(bpf_wasm.DLT_FC_2_WITH_FRAME_DELIMS)
	DLT_IPNET                      = LinkType(bpf_wasm.DLT_IPNET)
	DLT_CAN_SOCKETCAN              = LinkType(bpf_wasm.DLT_CAN_SOCKETCAN)
	DLT_IPV4                       = LinkType(bpf_wasm.DLT_IPV4)
	DLT_IPV6                       = LinkType(bpf_wasm.DLT_IPV6)
	DLT_IEEE802_15_4_NOFCS         = LinkType(bpf_wasm.DLT_IEEE802_15_4_NOFCS)
	DLT_DBUS                       = LinkType(bpf_wasm.DLT_DBUS)
	DLT_JUNIPER_VS                 = LinkType(bpf_wasm.DLT_JUNIPER_VS)
	DLT_JUNIPER_SRX_E2E            = LinkType(bpf_wasm.DLT_JUNIPER_SRX_E2E)
	DLT_JUNIPER_FIBRECHANNEL       = LinkType(bpf_wasm.DLT_JUNIPER_FIBRECHANNEL)
	DLT_DVB_CI                     = LinkType(bpf_wasm.DLT_DVB_CI)
	DLT_MUX27010                   = LinkType(bpf_wasm.DLT_MUX27010)
	DLT_STANAG_5066_D_PDU          = LinkType(bpf_wasm.DLT_STANAG_5066_D_PDU)
	DLT_JUNIPER_ATM_CEMIC          = LinkType(bpf_wasm.DLT_JUNIPER_ATM_CEMIC)
	DLT_NFLOG                      = LinkType(bpf_wasm.DLT_NFLOG)
	DLT_NETANALYZER                = LinkType(bpf_wasm.DLT_NETANALYZER)
	DLT_NETANALYZER_TRANSPARENT    = LinkType(bpf_wasm.DLT_NETANALYZER_TRANSPARENT)
	DLT_IPOIB                      = LinkType(bpf_wasm.DLT_IPOIB)
	DLT_MPEG_2_TS                  = LinkType(bpf_wasm.DLT_MPEG_2_TS)
	DLT_NG40                       = LinkType(bpf_wasm.DLT_NG40)
	DLT_NFC_LLCP                   = LinkType(bpf_wasm.DLT_NFC_LLCP)
	DLT_PFSYNC                     = LinkType(bpf_wasm.DLT_PFSYNC)
	DLT_INFINIBAND                 = LinkType(bpf_wasm.DLT_INFINIBAND)
	DLT_SCTP                       = LinkType(bpf_wasm.DLT_SCTP)
	DLT_USBPCAP                    = LinkType(bpf_wasm.DLT_USBPCAP)
	DLT_RTAC_SERIAL                = LinkType(bpf_wasm.DLT_RTAC_SERIAL)
	DLT_BLUETOOTH_LE_LL            = LinkType(bpf_wasm.DLT_BLUETOOTH_LE_LL)
	DLT_WIRESHARK_UPPER_PDU        = LinkType(bpf_wasm.DLT_WIRESHARK_UPPER_PDU)
	DLT_NETLINK                    = LinkType(bpf_wasm.DLT_NETLINK)
	DLT_BLUETOOTH_LINUX_MONITOR    = LinkType(bpf_wasm.DLT_BLUETOOTH_LINUX_MONITOR)
	DLT_BLUETOOTH_BREDR_BB         = LinkType(bpf_wasm.DLT_BLUETOOTH_BREDR_BB)
	DLT_BLUETOOTH_LE_LL_WITH_PHDR  = LinkType(bpf_wasm.DLT_BLUETOOTH_LE_LL_WITH_PHDR)
	DLT_PROFIBUS_DL                = LinkType(bpf_wasm.DLT_PROFIBUS_DL)
	DLT_PKTAP                      = LinkType(bpf_wasm.DLT_PKTAP)
	DLT_EPON                       = LinkType(bpf_wasm.DLT_EPON)
	DLT_IPMI_HPM_2                 = LinkType(bpf_wasm.DLT_IPMI_HPM_2)
	DLT_ZWAVE_R1_R2                = LinkType(bpf_wasm.DLT_ZWAVE_R1_R2)
	DLT_ZWAVE_R3                   = LinkType(bpf_wasm.DLT_ZWAVE_R3)
	DLT_WATTSTOPPER_DLM            = LinkType(bpf_wasm.DLT_WATTSTOPPER_DLM)
	DLT_ISO_14443                  = LinkType(bpf_wasm.DLT_ISO_14443)
	DLT_RDS                        = LinkType(bpf_wasm.DLT_RDS)
	DLT_USB_DARWIN                 = LinkType(bpf_wasm.DLT_USB_DARWIN)
	DLT_OPENFLOW                   = LinkType(bpf_wasm.DLT_OPENFLOW)
	DLT_SDLC                       = LinkType(bpf_wasm.DLT_SDLC)
	DLT_TI_LLN_SNIFFER             = LinkType(bpf_wasm.DLT_TI_LLN_SNIFFER)
	DLT_LORATAP                    = LinkType(bpf_wasm.DLT_LORATAP)
	DLT_VSOCK                      = LinkType(bpf_wasm.DLT_VSOCK)
	DLT_NORDIC_BLE                 = LinkType(bpf_wasm.DLT_NORDIC_BLE)
	DLT_DOCSIS31_XRA31             = LinkType(bpf_wasm.DLT_DOCSIS31_XRA31)
	DLT_ETHERNET_MPACKET           = LinkType(bpf_wasm.DLT_ETHERNET_MPACKET)
	DLT_DISPLAYPORT_AUX            = LinkType(bpf_wasm.DLT_DISPLAYPORT_AUX)
	DLT_LINUX_SLL2                 = LinkType(bpf_wasm.DLT_LINUX_SLL2)
	DLT_SERCOS_MONITOR             = LinkType(bpf_wasm.DLT_SERCOS_MONITOR)
	DLT_OPENVIZSLA                 = LinkType(bpf_wasm.DLT_OPENVIZSLA)
	DLT_EBHSCR                     = LinkType(bpf_wasm.DLT_EBHSCR)
	DLT_VPP_DISPATCH               = LinkType(bpf_wasm.DLT_VPP_DISPATCH)
	DLT_DSA_TAG_BRCM               = LinkType(bpf_wasm.DLT_DSA_TAG_BRCM)
	DLT_DSA_TAG_BRCM_PREPEND       = LinkType(bpf_wasm.DLT_DSA_TAG_BRCM_PREPEND)
	DLT_IEEE802_15_4_TAP           = LinkType(bpf_wasm.DLT_IEEE802_15_4_TAP)
	DLT_DSA_TAG_DSA                = LinkType(bpf_wasm.DLT_DSA_TAG_DSA)
	DLT_DSA_TAG_EDSA               = LinkType(bpf_wasm.DLT_DSA_TAG_EDSA)
	DLT_ELEE                       = LinkType(bpf_wasm.DLT_ELEE)
	DLT_Z_WAVE_SERIAL              = LinkType(bpf_wasm.DLT_Z_WAVE_SERIAL)
	DLT_USB_2_0                    = LinkType(bpf_wasm.DLT_USB_2_0)
	DLT_ATSC_ALP                   = LinkType(bpf_wasm.DLT_ATSC_ALP)
	DLT_ETW                        = LinkType(bpf_wasm.DLT_ETW)
	DLT_NETANALYZER_NG             = LinkType(bpf_wasm.DLT_NETANALYZER_NG)
	DLT_ZBOSS_NCP                  = LinkType(bpf_wasm.DLT_ZBOSS_NCP)
	DLT_USB_2_0_LOW_SPEED          = LinkType(bpf_wasm.DLT_USB_2_0_LOW_SPEED)
	DLT_USB_2_0_FULL_SPEED         = LinkType(bpf_wasm.DLT_USB_2_0_FULL_SPEED)
	DLT_USB_2_0_HIGH_SPEED         = LinkType(bpf_wasm.DLT_USB_2_0_HIGH_SPEED)
	DLT_AUERSWALD_LOG              = LinkType(bpf_wasm.DLT_AUERSWALD_LOG)
	DLT_ZWAVE_TAP                  = LinkType(bpf_wasm.DLT_ZWAVE_TAP)
	DLT_SILABS_DEBUG_CHANNEL       = LinkType(bpf_wasm.DLT_SILABS_DEBUG_CHANNEL)
	DLT_FIRA_UCI                   = LinkType(bpf_wasm.DLT_FIRA_UCI)
	DLT_MDB                        = LinkType(bpf_wasm.DLT_MDB)
	DLT_DECT_NR                    = LinkType(bpf_wasm.DLT_DECT_NR)
	DLT_EDK2_MM                    = LinkType(bpf_wasm.DLT_EDK2_MM)
	DLT_DEBUG_ONLY                 = LinkType(bpf_wasm.DLT_DEBUG_ONLY)
)

// LookupLinkType gets a link-layer type by name (e.g. "EN10MB" or "DLT_EN10MB") case-insensitively.
func LookupLinkType(name string) (LinkType, bool) {
	switch strings.TrimPrefix(strings.ToUpper(name), "DLT_") {
	case "NULL":
		return DLT_NULL, true
	case "EN10MB":
		return DLT_EN10MB, true
	case "EN3MB":
		return DLT_EN3MB, true
	case "AX25":
		return DLT_AX25, true
	case "PRONET":
		return DLT_PRONET, true
	case "CHAOS":
		return DLT_CHAOS, true
	case "IEEE802":
		return DLT_IEEE802, true
	case "ARCNET":
		return DLT_ARCNET, true
	case "SLIP":
		return DLT_SLIP, true
	case "PPP":
		return DLT_PPP, true
	case "FDDI":
		return DLT_FDDI, true
	case "ATM_RFC1483":
		return DLT_ATM_RFC1483, true
	case "RAW":
		return DLT_RAW, true
	case "SLIP_BSDOS":
		return DLT_SLIP_BSDOS, true
	case "PPP_BSDOS":
		return DLT_PPP_BSDOS, true
	case "ATM_CLIP":
		return DLT_ATM_CLIP, true
	case "REDBACK_SMARTEDGE":
		return DLT_REDBACK_SMARTEDGE, true
	case "PPP_SERIAL":
		return DLT_PPP_SERIAL, true
	case "PPP_ETHER":
		return DLT_PPP_ETHER, true
	case "SYMANTEC_FIREWALL":
		return DLT_SYMANTEC_FIREWALL, true
	case "C_HDLC":
		return DLT_C_HDLC, true
	case "IEEE802_11":
		return DLT_IEEE802_11, true
	case "FRELAY":
		return DLT_FRELAY, true
	case "LOOP":
		return DLT_LOOP, true
	case "ENC":
		return DLT_ENC, true
	case "HDLC":
		return DLT_HDLC, true
	case "LINUX_SLL":
		return DLT_LINUX_SLL, true
	case "LTALK":
		return DLT_LTALK, true
	case "ECONET":
		return DLT_ECONET, true
	case "IPFILTER":
		return DLT_IPFILTER, true
	case "PFLOG":
		return DLT_PFLOG, true
	case "CISCO_IOS":
		return DLT_CISCO_IOS, true
	case "PRISM_HEADER":
		return DLT_PRISM_HEADER, true
	case "AIRONET_HEADER":
		return DLT_AIRONET_HEADER, true
	case "HHDLC":
		return DLT_HHDLC, true
	case "IP_OVER_FC":
		return DLT_IP_OVER_FC, true
	case "SUNATM":
		return DLT_SUNATM, true
	case "RIO":
		return DLT_RIO, true
	case "PCI_EXP":
		return DLT_PCI_EXP, true
	case "AURORA":
		return DLT_AURORA, true
	case "IEEE802_11_RADIO":
		return DLT_IEEE802_11_RADIO, true
	case "TZSP":
		return DLT_TZSP, true
	case "ARCNET_LINUX":
		return DLT_ARCNET_LINUX, true
	case "JUNIPER_MLPPP":
		return DLT_JUNIPER_MLPPP, true
	case "JUNIPER_MLFR":
		return DLT_JUNIPER_MLFR, true
	case "JUNIPER_ES":
		return DLT_JUNIPER_ES, true
	case "JUNIPER_GGSN":
		return DLT_JUNIPER_GGSN, true
	case "JUNIPER_MFR":
		return DLT_JUNIPER_MFR, true
	case "JUNIPER_ATM2":
		return DLT_JUNIPER_ATM2, true
	case "JUNIPER_SERVICES":
		return DLT_JUNIPER_SERVICES, true
	case "JUNIPER_ATM1":
		return DLT_JUNIPER_ATM1, true
	case "APPLE_IP_OVER_IEEE1394":
		return DLT_APPLE_IP_OVER_IEEE1394, true
	case "MTP2_WITH_PHDR":
		return DLT_MTP2_WITH_PHDR, true
	case "MTP2":
		return DLT_MTP2, true
	case "MTP3":
		return DLT_MTP3, true
	case "SCCP":
		return DLT_SCCP, true
	case "DOCSIS":
		return DLT_DOCSIS, true
	case "LINUX_IRDA":
		return DLT_LINUX_IRDA, true
	case "IBM_SP":
		return DLT_IBM_SP, true
	case "IBM_SN":
		return DLT_IBM_SN, true
	case "USER0":
		return DLT_USER0, true
	case "USER1":
		return DLT_USER1, true
	case "USER2":
		return DLT_USER2, true
	case "USER3":
		return DLT_USER3, true
	case "USER4":
		return DLT_USER4, true
	case "USER5":
		return DLT_USER5, true
	case "USER6":
		return DLT_USER6, true
	case "USER7":
		return DLT_USER7, true
	case "USER8":
		return DLT_USER8, true
	case "USER9":
		return DLT_USER9, true
	case "USER10":
		return DLT_USER10, true
	case "USER11":
		return DLT_USER11, true
	case "USER12":
		return DLT_USER12, true
	case "USER13":
		return DLT_USER13, true
	case "USER14":
		return DLT_USER14, true
	case "USER15":
		return DLT_USER15, true
	case "IEEE802_11_RADIO_AVS":
		return DLT_IEEE802_11_RADIO_AVS, true
	case "JUNIPER_MONITOR":
		return DLT_JUNIPER_MONITOR, true
	case "BACNET_MS_TP":
		return DLT_BACNET_MS_TP, true
	case "PPP_PPPD":
		return DLT_PPP_PPPD, true
	case "JUNIPER_PPPOE":
		return DLT_JUNIPER_PPPOE, true
	case "JUNIPER_PPPOE_ATM":
		return DLT_JUNIPER_PPPOE_ATM, true
	case "GPRS_LLC":
		return DLT_GPRS_LLC, true
	case "GPF_T":
		return DLT_GPF_T, true
	case "GPF_F":
		return DLT_GPF_F, true
	case "GCOM_T1E1":
		return DLT_GCOM_T1E1, true
	case "GCOM_SERIAL":
		return DLT_GCOM_SERIAL, true
	case "JUNIPER_PIC_PEER":
		return DLT_JUNIPER_PIC_PEER, true
	case "ERF_ETH":
		return DLT_ERF_ETH, true
	case "ERF_POS":
		return DLT_ERF_POS, true
	case "LINUX_LAPD":
		return DLT_LINUX_LAPD, true
	case "JUNIPER_ETHER":
		return DLT_JUNIPER_ETHER, true
	case "JUNIPER_PPP":
		return DLT_JUNIPER_PPP, true
	case "JUNIPER_FRELAY":
		return DLT_JUNIPER_FRELAY, true
	case "JUNIPER_CHDLC":
		return DLT_JUNIPER_CHDLC, true
	case "MFR":
		return DLT_MFR, true
	case "JUNIPER_VP":
		return DLT_JUNIPER_VP, true
	case "A429":
		return DLT_A429, true
	case "A653_ICM":
		return DLT_A653_ICM, true
	case "USB":
		return DLT_USB, true
	case "USB_FREEBSD":
		return DLT_USB_FREEBSD, true
	case "BLUETOOTH_HCI_H4":
		return DLT_BLUETOOTH_HCI_H4, true
	case "IEEE802_16_MAC_CPS":
		return DLT_IEEE802_16_MAC_CPS, true
	case "USB_LINUX":
		return DLT_USB_LINUX, true
	case "CAN20B":
		return DLT_CAN20B, true
	case "IEEE802_15_4_LINUX":
		return DLT_IEEE802_15_4_LINUX, true
	case "PPI":
		return DLT_PPI, true
	case "IEEE802_16_MAC_CPS_RADIO":
		return DLT_IEEE802_16_MAC_CPS_RADIO, true
	case "JUNIPER_ISM":
		return DLT_JUNIPER_ISM, true
	case "IEEE802_15_4_WITHFCS":
		return DLT_IEEE802_15_4_WITHFCS, true
	case "SITA":
		return DLT_SITA, true
	case "ERF":
		return DLT_ERF, true
	case "RAIF1":
		return DLT_RAIF1, true
	case "IPMB_KONTRON":
		return DLT_IPMB_KONTRON, true
	case "JUNIPER_ST":
		return DLT_JUNIPER_ST, true
	case "BLUETOOTH_HCI_H4_WITH_PHDR":
		return DLT_BLUETOOTH_HCI_H4_WITH_PHDR, true
	case "AX25_KISS":
		return DLT_AX25_KISS, true
	case "LAPD":
		return DLT_LAPD, true
	case "PPP_WITH_DIR":
		return DLT_PPP_WITH_DIR, true
	case "C_HDLC_WITH_DIR":
		return DLT_C_HDLC_WITH_DIR, true
	case "FRELAY_WITH_DIR":
		return DLT_FRELAY_WITH_DIR, true
	case "LAPB_WITH_DIR":
		return DLT_LAPB_WITH_DIR, true
	case "I2C_LINUX":
		return DLT_I2C_LINUX, true
	case "IPMB_LINUX":
		return DLT_IPMB_LINUX, true
	case "FLEXRAY":
		return DLT_FLEXRAY, true
	case "MOST":
		return DLT_MOST, true
	case "LIN":
		return DLT_LIN, true
	case "X2E_SERIAL":
		return DLT_X2E_SERIAL, true
	case "X2E_XORAYA":
		return DLT_X2E_XORAYA, true
	case "IEEE802_15_4_NONASK_PHY":
		return DLT_IEEE802_15_4_NONASK_PHY, true
	case "LINUX_EVDEV":
		return DLT_LINUX_EVDEV, true
	case "GSMTAP_UM":
		return DLT_GSMTAP_UM, true
	case "GSMTAP_ABIS":
		return DLT_GSMTAP_ABIS, true
	case "MPLS":
		return DLT_MPLS, true
	case "USB_LINUX_MMAPPED":
		return DLT_USB_LINUX_MMAPPED, true
	case "DECT":
		return DLT_DECT, true
	case "AOS":
		return DLT_AOS, true
	case "WIHART":
		return DLT_WIHART, true
	case "FC_2":
		return DLT_FC_2, true
	case "FC_2_WITH_FRAME_DELIMS":
		return DLT_FC_2_WITH_FRAME_DELIMS, true
	case "IPNET":
		return DLT_IPNET, true
	case "CAN_SOCKETCAN":
		return DLT_CAN_SOCKETCAN, true
	case "IPV4":
		return DLT_IPV4, true
	case "IPV6":
		return DLT_IPV6, true
	case "IEEE802_15_4_NOFCS":
		return DLT_IEEE802_15_4_NOFCS, true
	case "DBUS":
		return DLT_DBUS, true
	case "JUNIPER_VS":
		return DLT_JUNIPER_VS, true
	case "JUNIPER_SRX_E2E":
		return DLT_JUNIPER_SRX_E2E, true
	case "JUNIPER_FIBRECHANNEL":
		return DLT_JUNIPER_FIBRECHANNEL, true
	case "DVB_CI":
		return DLT_DVB_CI, true
	case "MUX27010":
		return DLT_MUX27010, true
	case "STANAG_5066_D_PDU":
		return DLT_STANAG_5066_D_PDU, true
	case "JUNIPER_ATM_CEMIC":
		return DLT_JUNIPER_ATM_CEMIC, true
	case "NFLOG":
		return DLT_NFLOG, true
	case "NETANALYZER":
		return DLT_NETANALYZER, true
	case "NETANALYZER_TRANSPARENT":
		return DLT_NETANALYZER_TRANSPARENT, true
	case "IPOIB":
		return DLT_IPOIB, true
	case "MPEG_2_TS":
		return DLT_MPEG_2_TS, true
	case "NG40":
		return DLT_NG40, true
	case "NFC_LLCP":
		return DLT_NFC_LLCP, true
	case "PFSYNC":
		return DLT_PFSYNC, true
	case "INFINIBAND":
		return DLT_INFINIBAND, true
	case "SCTP":
		return DLT_SCTP, true
	case "USBPCAP":
		return DLT_USBPCAP, true
	case "RTAC_SERIAL":
		return DLT_RTAC_SERIAL, true
	case "BLUETOOTH_LE_LL":
		return DLT_BLUETOOTH_LE_LL, true
	case "WIRESHARK_UPPER_PDU":
		return DLT_WIRESHARK_UPPER_PDU, true
	case "NETLINK":
		return DLT_NETLINK, true
	case "BLUETOOTH_LINUX_MONITOR":
		return DLT_BLUETOOTH_LINUX_MONITOR, true
	case "BLUETOOTH_BREDR_BB":
		return DLT_BLUETOOTH_BREDR_BB, true
	case "BLUETOOTH_LE_LL_WITH_PHDR":
		return DLT_BLUETOOTH_LE_LL_WITH_PHDR, true
	case "PROFIBUS_DL":
		return DLT_PROFIBUS_DL, true
	case "PKTAP":
		return DLT_PKTAP, true
	case "EPON":
		return DLT_EPON, true
	case "IPMI_HPM_2":
		return DLT_IPMI_HPM_2, true
	case "ZWAVE_R1_R2":
		return DLT_ZWAVE_R1_R2, true
	case "ZWAVE_R3":
		return DLT_ZWAVE_R3, true
	case "WATTSTOPPER_DLM":
		return DLT_WATTSTOPPER_DLM, true
	case "ISO_14443":
		return DLT_ISO_14443, true
	case "RDS":
		return DLT_RDS, true
	case "USB_DARWIN":
		return DLT_USB_DARWIN, true
	case "OPENFLOW":
		return DLT_OPENFLOW, true
	case "SDLC":
		return DLT_SDLC, true
	case "TI_LLN_SNIFFER":
		return DLT_TI_LLN_SNIFFER, true
	case "LORATAP":
		return DLT_LORATAP, true
	case "VSOCK":
		return DLT_VSOCK, true
	case "NORDIC_BLE":
		return DLT_NORDIC_BLE, true
	case "DOCSIS31_XRA31":
		return DLT_DOCSIS31_XRA31, true
	case "ETHERNET_MPACKET":
		return DLT_ETHERNET_MPACKET, true
	case "DISPLAYPORT_AUX":
		return DLT_DISPLAYPORT_AUX, true
	case "LINUX_SLL2":
		return DLT_LINUX_SLL2, true
	case "SERCOS_MONITOR":
		return DLT_SERCOS_MONITOR, true
	case "OPENVIZSLA":
		return DLT_OPENVIZSLA, true
	case "EBHSCR":
		return DLT_EBHSCR, true
	case "VPP_DISPATCH":
		return DLT_VPP_DISPATCH, true
	case "DSA_TAG_BRCM":
		return DLT_DSA_TAG_BRCM, true
	case "DSA_TAG_BRCM_PREPEND":
		return DLT_DSA_TAG_BRCM_PREPEND, true
	case "IEEE802_15_4_TAP":
		return DLT_IEEE802_15_4_TAP, true
	case "DSA_TAG_DSA":
		return DLT_DSA_TAG_DSA, true
	case "DSA_TAG_EDSA":
		return DLT_DSA_TAG_EDSA, true
	case "ELEE":
		return DLT_ELEE, true
	case "Z_WAVE_SERIAL":
		return DLT_Z_WAVE_SERIAL, true
	case "USB_2_0":
		return DLT_USB_2_0, true
	case "ATSC_ALP":
		return DLT_ATSC_ALP, true
	case "ETW":
		return DLT_ETW, true
	case "NETANALYZER_NG":
		return DLT_NETANALYZER_NG, true
	case "ZBOSS_NCP":
		return DLT_ZBOSS_NCP, true
	case "USB_2_0_LOW_SPEED":
		return DLT_USB_2_0_LOW_SPEED, true
	case "USB_2_0_FULL_SPEED":
		return DLT_USB_2_0_FULL_SPEED, true
	case "USB_2_0_HIGH_SPEED":
		return DLT_USB_2_0_HIGH_SPEED, true
	case "AUERSWALD_LOG":
		return DLT_AUERSWALD_LOG, true
	case "ZWAVE_TAP":
		return DLT_ZWAVE_TAP, true
	case "SILABS_DEBUG_CHANNEL":
		return DLT_SILABS_DEBUG_CHANNEL, true
	case "FIRA_UCI":
		return DLT_FIRA_UCI, true
	case "MDB":
		return DLT_MDB, true
	case "DECT_NR":
		return DLT_DECT_NR, true
	case "EDK2_MM":
		return DLT_EDK2_MM, true
	case "DEBUG_ONLY":
		return DLT_DEBUG_ONLY, true
	default:
		return 0, false
	}
}
