// Code generated by dlt; DO NOT EDIT.

package pcapfilter

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/pgaskin/go-pcapfilter/internal"
)

const (
	DLT_NULL                       = LinkType(bpf_wasm.DLT_NULL)
	DLT_EN10MB                     = LinkType(bpf_wasm.DLT_EN10MB)
	DLT_EN3MB                      = LinkType(bpf_wasm.DLT_EN3MB)
	DLT_AX25                       = LinkType(bpf_wasm.DLT_AX25)
	DLT_PRONET                     = LinkType(bpf_wasm.DLT_PRONET)
	DLT_CHAOS                      = LinkType(bpf_wasm.DLT_CHAOS)
	DLT_IEEE802                    = LinkType(bpf_wasm.DLT_IEEE802)
	DLT_ARCNET                     = LinkType(bpf_wasm.DLT_ARCNET)
	DLT_SLIP                       = LinkType(bpf_wasm.DLT_SLIP)
	DLT_PPP                        = LinkType(bpf_wasm.DLT_PPP)
	DLT_FDDI                       = LinkType(bpf_wasm.DLT_FDDI)
	DLT_ATM_RFC1483                = LinkType(bpf_wasm.DLT_ATM_RFC1483)
	DLT_RAW                        = LinkType(bpf_wasm.DLT_RAW)
	DLT_SLIP_BSDOS                 = LinkType(bpf_wasm.DLT_SLIP_BSDOS)
	DLT_PPP_BSDOS                  = LinkType(bpf_wasm.DLT_PPP_BSDOS)
	DLT_ATM_CLIP                   = LinkType(bpf_wasm.DLT_ATM_CLIP)
	DLT_REDBACK_SMARTEDGE          = LinkType(bpf_wasm.DLT_REDBACK_SMARTEDGE)
	DLT_PPP_SERIAL                 = LinkType(bpf_wasm.DLT_PPP_SERIAL)
	DLT_PPP_ETHER                  = LinkType(bpf_wasm.DLT_PPP_ETHER)
	DLT_SYMANTEC_FIREWALL          = LinkType(bpf_wasm.DLT_SYMANTEC_FIREWALL)
	DLT_C_HDLC                     = LinkType(bpf_wasm.DLT_C_HDLC)
	DLT_IEEE802_11                 = LinkType(bpf_wasm.DLT_IEEE802_11)
	DLT_FRELAY                     = LinkType(bpf_wasm.DLT_FRELAY)
	DLT_LOOP                       = LinkType(bpf_wasm.DLT_LOOP)
	DLT_ENC                        = LinkType(bpf_wasm.DLT_ENC)
	DLT_HDLC                       = LinkType(bpf_wasm.DLT_HDLC)
	DLT_LINUX_SLL                  = LinkType(bpf_wasm.DLT_LINUX_SLL)
	DLT_LTALK                      = LinkType(bpf_wasm.DLT_LTALK)
	DLT_ECONET                     = LinkType(bpf_wasm.DLT_ECONET)
	DLT_IPFILTER                   = LinkType(bpf_wasm.DLT_IPFILTER)
	DLT_PFLOG                      = LinkType(bpf_wasm.DLT_PFLOG)
	DLT_CISCO_IOS                  = LinkType(bpf_wasm.DLT_CISCO_IOS)
	DLT_PRISM_HEADER               = LinkType(bpf_wasm.DLT_PRISM_HEADER)
	DLT_AIRONET_HEADER             = LinkType(bpf_wasm.DLT_AIRONET_HEADER)
	DLT_HHDLC                      = LinkType(bpf_wasm.DLT_HHDLC)
	DLT_IP_OVER_FC                 = LinkType(bpf_wasm.DLT_IP_OVER_FC)
	DLT_SUNATM                     = LinkType(bpf_wasm.DLT_SUNATM)
	DLT_RIO                        = LinkType(bpf_wasm.DLT_RIO)
	DLT_PCI_EXP                    = LinkType(bpf_wasm.DLT_PCI_EXP)
	DLT_AURORA                     = LinkType(bpf_wasm.DLT_AURORA)
	DLT_IEEE802_11_RADIO           = LinkType(bpf_wasm.DLT_IEEE802_11_RADIO)
	DLT_TZSP                       = LinkType(bpf_wasm.DLT_TZSP)
	DLT_ARCNET_LINUX               = LinkType(bpf_wasm.DLT_ARCNET_LINUX)
	DLT_JUNIPER_MLPPP              = LinkType(bpf_wasm.DLT_JUNIPER_MLPPP)
	DLT_JUNIPER_MLFR               = LinkType(bpf_wasm.DLT_JUNIPER_MLFR)
	DLT_JUNIPER_ES                 = LinkType(bpf_wasm.DLT_JUNIPER_ES)
	DLT_JUNIPER_GGSN               = LinkType(bpf_wasm.DLT_JUNIPER_GGSN)
	DLT_JUNIPER_MFR                = LinkType(bpf_wasm.DLT_JUNIPER_MFR)
	DLT_JUNIPER_ATM2               = LinkType(bpf_wasm.DLT_JUNIPER_ATM2)
	DLT_JUNIPER_SERVICES           = LinkType(bpf_wasm.DLT_JUNIPER_SERVICES)
	DLT_JUNIPER_ATM1               = LinkType(bpf_wasm.DLT_JUNIPER_ATM1)
	DLT_APPLE_IP_OVER_IEEE1394     = LinkType(bpf_wasm.DLT_APPLE_IP_OVER_IEEE1394)
	DLT_MTP2_WITH_PHDR             = LinkType(bpf_wasm.DLT_MTP2_WITH_PHDR)
	DLT_MTP2                       = LinkType(bpf_wasm.DLT_MTP2)
	DLT_MTP3                       = LinkType(bpf_wasm.DLT_MTP3)
	DLT_SCCP                       = LinkType(bpf_wasm.DLT_SCCP)
	DLT_DOCSIS                     = LinkType(bpf_wasm.DLT_DOCSIS)
	DLT_LINUX_IRDA                 = LinkType(bpf_wasm.DLT_LINUX_IRDA)
	DLT_IBM_SP                     = LinkType(bpf_wasm.DLT_IBM_SP)
	DLT_IBM_SN                     = LinkType(bpf_wasm.DLT_IBM_SN)
	DLT_USER0                      = LinkType(bpf_wasm.DLT_USER0)
	DLT_USER1                      = LinkType(bpf_wasm.DLT_USER1)
	DLT_USER2                      = LinkType(bpf_wasm.DLT_USER2)
	DLT_USER3                      = LinkType(bpf_wasm.DLT_USER3)
	DLT_USER4                      = LinkType(bpf_wasm.DLT_USER4)
	DLT_USER5                      = LinkType(bpf_wasm.DLT_USER5)
	DLT_USER6                      = LinkType(bpf_wasm.DLT_USER6)
	DLT_USER7                      = LinkType(bpf_wasm.DLT_USER7)
	DLT_USER8                      = LinkType(bpf_wasm.DLT_USER8)
	DLT_USER9                      = LinkType(bpf_wasm.DLT_USER9)
	DLT_USER10                     = LinkType(bpf_wasm.DLT_USER10)
	DLT_USER11                     = LinkType(bpf_wasm.DLT_USER11)
	DLT_USER12                     = LinkType(bpf_wasm.DLT_USER12)
	DLT_USER13                     = LinkType(bpf_wasm.DLT_USER13)
	DLT_USER14                     = LinkType(bpf_wasm.DLT_USER14)
	DLT_USER15                     = LinkType(bpf_wasm.DLT_USER15)
	DLT_IEEE802_11_RADIO_AVS       = LinkType(bpf_wasm.DLT_IEEE802_11_RADIO_AVS)
	DLT_JUNIPER_MONITOR            = LinkType(bpf_wasm.DLT_JUNIPER_MONITOR)
	DLT_BACNET_MS_TP               = LinkType(bpf_wasm.DLT_BACNET_MS_TP)
	DLT_PPP_PPPD                   = LinkType(bpf_wasm.DLT_PPP_PPPD)
	DLT_JUNIPER_PPPOE              = LinkType(bpf_wasm.DLT_JUNIPER_PPPOE)
	DLT_JUNIPER_PPPOE_ATM          = LinkType(bpf_wasm.DLT_JUNIPER_PPPOE_ATM)
	DLT_GPRS_LLC                   = LinkType(bpf_wasm.DLT_GPRS_LLC)
	DLT_GPF_T                      = LinkType(bpf_wasm.DLT_GPF_T)
	DLT_GPF_F                      = LinkType(bpf_wasm.DLT_GPF_F)
	DLT_GCOM_T1E1                  = LinkType(bpf_wasm.DLT_GCOM_T1E1)
	DLT_GCOM_SERIAL                = LinkType(bpf_wasm.DLT_GCOM_SERIAL)
	DLT_JUNIPER_PIC_PEER           = LinkType(bpf_wasm.DLT_JUNIPER_PIC_PEER)
	DLT_ERF_ETH                    = LinkType(bpf_wasm.DLT_ERF_ETH)
	DLT_ERF_POS                    = LinkType(bpf_wasm.DLT_ERF_POS)
	DLT_LINUX_LAPD                 = LinkType(bpf_wasm.DLT_LINUX_LAPD)
	DLT_JUNIPER_ETHER              = LinkType(bpf_wasm.DLT_JUNIPER_ETHER)
	DLT_JUNIPER_PPP                = LinkType(bpf_wasm.DLT_JUNIPER_PPP)
	DLT_JUNIPER_FRELAY             = LinkType(bpf_wasm.DLT_JUNIPER_FRELAY)
	DLT_JUNIPER_CHDLC              = LinkType(bpf_wasm.DLT_JUNIPER_CHDLC)
	DLT_MFR                        = LinkType(bpf_wasm.DLT_MFR)
	DLT_JUNIPER_VP                 = LinkType(bpf_wasm.DLT_JUNIPER_VP)
	DLT_A429                       = LinkType(bpf_wasm.DLT_A429)
	DLT_A653_ICM                   = LinkType(bpf_wasm.DLT_A653_ICM)
	DLT_USB                        = LinkType(bpf_wasm.DLT_USB)
	DLT_USB_FREEBSD                = LinkType(bpf_wasm.DLT_USB_FREEBSD)
	DLT_BLUETOOTH_HCI_H4           = LinkType(bpf_wasm.DLT_BLUETOOTH_HCI_H4)
	DLT_IEEE802_16_MAC_CPS         = LinkType(bpf_wasm.DLT_IEEE802_16_MAC_CPS)
	DLT_USB_LINUX                  = LinkType(bpf_wasm.DLT_USB_LINUX)
	DLT_CAN20B                     = LinkType(bpf_wasm.DLT_CAN20B)
	DLT_IEEE802_15_4_LINUX         = LinkType(bpf_wasm.DLT_IEEE802_15_4_LINUX)
	DLT_PPI                        = LinkType(bpf_wasm.DLT_PPI)
	DLT_IEEE802_16_MAC_CPS_RADIO   = LinkType(bpf_wasm.DLT_IEEE802_16_MAC_CPS_RADIO)
	DLT_JUNIPER_ISM                = LinkType(bpf_wasm.DLT_JUNIPER_ISM)
	DLT_IEEE802_15_4_WITHFCS       = LinkType(bpf_wasm.DLT_IEEE802_15_4_WITHFCS)
	DLT_SITA                       = LinkType(bpf_wasm.DLT_SITA)
	DLT_ERF                        = LinkType(bpf_wasm.DLT_ERF)
	DLT_RAIF1                      = LinkType(bpf_wasm.DLT_RAIF1)
	DLT_IPMB_KONTRON               = LinkType(bpf_wasm.DLT_IPMB_KONTRON)
	DLT_JUNIPER_ST                 = LinkType(bpf_wasm.DLT_JUNIPER_ST)
	DLT_BLUETOOTH_HCI_H4_WITH_PHDR = LinkType(bpf_wasm.DLT_BLUETOOTH_HCI_H4_WITH_PHDR)
	DLT_AX25_KISS                  = LinkType(bpf_wasm.DLT_AX25_KISS)
	DLT_LAPD                       = LinkType(bpf_wasm.DLT_LAPD)
	DLT_PPP_WITH_DIR               = LinkType(bpf_wasm.DLT_PPP_WITH_DIR)
	DLT_C_HDLC_WITH_DIR            = LinkType(bpf_wasm.DLT_C_HDLC_WITH_DIR)
	DLT_FRELAY_WITH_DIR            = LinkType(bpf_wasm.DLT_FRELAY_WITH_DIR)
	DLT_LAPB_WITH_DIR              = LinkType(bpf_wasm.DLT_LAPB_WITH_DIR)
	DLT_I2C_LINUX                  = LinkType(bpf_wasm.DLT_I2C_LINUX)
	DLT_IPMB_LINUX                 = LinkType(bpf_wasm.DLT_IPMB_LINUX)
	DLT_FLEXRAY                    = LinkType(bpf_wasm.DLT_FLEXRAY)
	DLT_MOST                       = LinkType(bpf_wasm.DLT_MOST)
	DLT_LIN                        = LinkType(bpf_wasm.DLT_LIN)
	DLT_X2E_SERIAL                 = LinkType(bpf_wasm.DLT_X2E_SERIAL)
	DLT_X2E_XORAYA                 = LinkType(bpf_wasm.DLT_X2E_XORAYA)
	DLT_IEEE802_15_4_NONASK_PHY    = LinkType(bpf_wasm.DLT_IEEE802_15_4_NONASK_PHY)
	DLT_LINUX_EVDEV                = LinkType(bpf_wasm.DLT_LINUX_EVDEV)
	DLT_GSMTAP_UM                  = LinkType(bpf_wasm.DLT_GSMTAP_UM)
	DLT_GSMTAP_ABIS                = LinkType(bpf_wasm.DLT_GSMTAP_ABIS)
	DLT_MPLS                       = LinkType(bpf_wasm.DLT_MPLS)
	DLT_USB_LINUX_MMAPPED          = LinkType(bpf_wasm.DLT_USB_LINUX_MMAPPED)
	DLT_DECT                       = LinkType(bpf_wasm.DLT_DECT)
	DLT_AOS                        = LinkType(bpf_wasm.DLT_AOS)
	DLT_WIHART                     = LinkType(bpf_wasm.DLT_WIHART)
	DLT_FC_2                       = LinkType(bpf_wasm.DLT_FC_2)
	DLT_FC_2_WITH_FRAME_DELIMS     = LinkType(bpf_wasm.DLT_FC_2_WITH_FRAME_DELIMS)
	DLT_IPNET                      = LinkType(bpf_wasm.DLT_IPNET)
	DLT_CAN_SOCKETCAN              = LinkType(bpf_wasm.DLT_CAN_SOCKETCAN)
	DLT_IPV4                       = LinkType(bpf_wasm.DLT_IPV4)
	DLT_IPV6                       = LinkType(bpf_wasm.DLT_IPV6)
	DLT_IEEE802_15_4_NOFCS         = LinkType(bpf_wasm.DLT_IEEE802_15_4_NOFCS)
	DLT_DBUS                       = LinkType(bpf_wasm.DLT_DBUS)
	DLT_JUNIPER_VS                 = LinkType(bpf_wasm.DLT_JUNIPER_VS)
	DLT_JUNIPER_SRX_E2E            = LinkType(bpf_wasm.DLT_JUNIPER_SRX_E2E)
	DLT_JUNIPER_FIBRECHANNEL       = LinkType(bpf_wasm.DLT_JUNIPER_FIBRECHANNEL)
	DLT_DVB_CI                     = LinkType(bpf_wasm.DLT_DVB_CI)
	DLT_MUX27010                   = LinkType(bpf_wasm.DLT_MUX27010)
	DLT_STANAG_5066_D_PDU          = LinkType(bpf_wasm.DLT_STANAG_5066_D_PDU)
	DLT_JUNIPER_ATM_CEMIC          = LinkType(bpf_wasm.DLT_JUNIPER_ATM_CEMIC)
	DLT_NFLOG                      = LinkType(bpf_wasm.DLT_NFLOG)
	DLT_NETANALYZER                = LinkType(bpf_wasm.DLT_NETANALYZER)
	DLT_NETANALYZER_TRANSPARENT    = LinkType(bpf_wasm.DLT_NETANALYZER_TRANSPARENT)
	DLT_IPOIB                      = LinkType(bpf_wasm.DLT_IPOIB)
	DLT_MPEG_2_TS                  = LinkType(bpf_wasm.DLT_MPEG_2_TS)
	DLT_NG40                       = LinkType(bpf_wasm.DLT_NG40)
	DLT_NFC_LLCP                   = LinkType(bpf_wasm.DLT_NFC_LLCP)
	DLT_PFSYNC                     = LinkType(bpf_wasm.DLT_PFSYNC)
	DLT_INFINIBAND                 = LinkType(bpf_wasm.DLT_INFINIBAND)
	DLT_SCTP                       = LinkType(bpf_wasm.DLT_SCTP)
	DLT_USBPCAP                    = LinkType(bpf_wasm.DLT_USBPCAP)
	DLT_RTAC_SERIAL                = LinkType(bpf_wasm.DLT_RTAC_SERIAL)
	DLT_BLUETOOTH_LE_LL            = LinkType(bpf_wasm.DLT_BLUETOOTH_LE_LL)
	DLT_WIRESHARK_UPPER_PDU        = LinkType(bpf_wasm.DLT_WIRESHARK_UPPER_PDU)
	DLT_NETLINK                    = LinkType(bpf_wasm.DLT_NETLINK)
	DLT_BLUETOOTH_LINUX_MONITOR    = LinkType(bpf_wasm.DLT_BLUETOOTH_LINUX_MONITOR)
	DLT_BLUETOOTH_BREDR_BB         = LinkType(bpf_wasm.DLT_BLUETOOTH_BREDR_BB)
	DLT_BLUETOOTH_LE_LL_WITH_PHDR  = LinkType(bpf_wasm.DLT_BLUETOOTH_LE_LL_WITH_PHDR)
	DLT_PROFIBUS_DL                = LinkType(bpf_wasm.DLT_PROFIBUS_DL)
	DLT_PKTAP                      = LinkType(bpf_wasm.DLT_PKTAP)
	DLT_EPON                       = LinkType(bpf_wasm.DLT_EPON)
	DLT_IPMI_HPM_2                 = LinkType(bpf_wasm.DLT_IPMI_HPM_2)
	DLT_ZWAVE_R1_R2                = LinkType(bpf_wasm.DLT_ZWAVE_R1_R2)
	DLT_ZWAVE_R3                   = LinkType(bpf_wasm.DLT_ZWAVE_R3)
	DLT_WATTSTOPPER_DLM            = LinkType(bpf_wasm.DLT_WATTSTOPPER_DLM)
	DLT_ISO_14443                  = LinkType(bpf_wasm.DLT_ISO_14443)
	DLT_RDS                        = LinkType(bpf_wasm.DLT_RDS)
	DLT_USB_DARWIN                 = LinkType(bpf_wasm.DLT_USB_DARWIN)
	DLT_OPENFLOW                   = LinkType(bpf_wasm.DLT_OPENFLOW)
	DLT_SDLC                       = LinkType(bpf_wasm.DLT_SDLC)
	DLT_TI_LLN_SNIFFER             = LinkType(bpf_wasm.DLT_TI_LLN_SNIFFER)
	DLT_LORATAP                    = LinkType(bpf_wasm.DLT_LORATAP)
	DLT_VSOCK                      = LinkType(bpf_wasm.DLT_VSOCK)
	DLT_NORDIC_BLE                 = LinkType(bpf_wasm.DLT_NORDIC_BLE)
	DLT_DOCSIS31_XRA31             = LinkType(bpf_wasm.DLT_DOCSIS31_XRA31)
	DLT_ETHERNET_MPACKET           = LinkType(bpf_wasm.DLT_ETHERNET_MPACKET)
	DLT_DISPLAYPORT_AUX            = LinkType(bpf_wasm.DLT_DISPLAYPORT_AUX)
	DLT_LINUX_SLL2                 = LinkType(bpf_wasm.DLT_LINUX_SLL2)
	DLT_SERCOS_MONITOR             = LinkType(bpf_wasm.DLT_SERCOS_MONITOR)
	DLT_OPENVIZSLA                 = LinkType(bpf_wasm.DLT_OPENVIZSLA)
	DLT_EBHSCR                     = LinkType(bpf_wasm.DLT_EBHSCR)
	DLT_VPP_DISPATCH               = LinkType(bpf_wasm.DLT_VPP_DISPATCH)
	DLT_DSA_TAG_BRCM               = LinkType(bpf_wasm.DLT_DSA_TAG_BRCM)
	DLT_DSA_TAG_BRCM_PREPEND       = LinkType(bpf_wasm.DLT_DSA_TAG_BRCM_PREPEND)
	DLT_IEEE802_15_4_TAP           = LinkType(bpf_wasm.DLT_IEEE802_15_4_TAP)
	DLT_DSA_TAG_DSA                = LinkType(bpf_wasm.DLT_DSA_TAG_DSA)
	DLT_DSA_TAG_EDSA               = LinkType(bpf_wasm.DLT_DSA_TAG_EDSA)
	DLT_ELEE                       = LinkType(bpf_wasm.DLT_ELEE)
	DLT_Z_WAVE_SERIAL              = LinkType(bpf_wasm.DLT_Z_WAVE_SERIAL)
	DLT_USB_2_0                    = LinkType(bpf_wasm.DLT_USB_2_0)
	DLT_ATSC_ALP                   = LinkType(bpf_wasm.DLT_ATSC_ALP)
	DLT_ETW                        = LinkType(bpf_wasm.DLT_ETW)
	DLT_NETANALYZER_NG             = LinkType(bpf_wasm.DLT_NETANALYZER_NG)
	DLT_ZBOSS_NCP                  = LinkType(bpf_wasm.DLT_ZBOSS_NCP)
	DLT_USB_2_0_LOW_SPEED          = LinkType(bpf_wasm.DLT_USB_2_0_LOW_SPEED)
	DLT_USB_2_0_FULL_SPEED         = LinkType(bpf_wasm.DLT_USB_2_0_FULL_SPEED)
	DLT_USB_2_0_HIGH_SPEED         = LinkType(bpf_wasm.DLT_USB_2_0_HIGH_SPEED)
	DLT_AUERSWALD_LOG              = LinkType(bpf_wasm.DLT_AUERSWALD_LOG)
	DLT_ZWAVE_TAP                  = LinkType(bpf_wasm.DLT_ZWAVE_TAP)
	DLT_SILABS_DEBUG_CHANNEL       = LinkType(bpf_wasm.DLT_SILABS_DEBUG_CHANNEL)
	DLT_FIRA_UCI                   = LinkType(bpf_wasm.DLT_FIRA_UCI)
	DLT_MDB                        = LinkType(bpf_wasm.DLT_MDB)
	DLT_DECT_NR                    = LinkType(bpf_wasm.DLT_DECT_NR)
	DLT_EDK2_MM                    = LinkType(bpf_wasm.DLT_EDK2_MM)
	DLT_DEBUG_ONLY                 = LinkType(bpf_wasm.DLT_DEBUG_ONLY)
)

// UnmarshalText parses a link-layer type by name (e.g. "EN10MB" or "DLT_EN10MB") or integer.
func (t *LinkType) UnmarshalText(buf []byte) error {
	switch strings.TrimPrefix(strings.ToUpper(string(buf)), "DLT_") {
	case "NULL":
		*t = DLT_NULL
		return nil
	case "EN10MB":
		*t = DLT_EN10MB
		return nil
	case "EN3MB":
		*t = DLT_EN3MB
		return nil
	case "AX25":
		*t = DLT_AX25
		return nil
	case "PRONET":
		*t = DLT_PRONET
		return nil
	case "CHAOS":
		*t = DLT_CHAOS
		return nil
	case "IEEE802":
		*t = DLT_IEEE802
		return nil
	case "ARCNET":
		*t = DLT_ARCNET
		return nil
	case "SLIP":
		*t = DLT_SLIP
		return nil
	case "PPP":
		*t = DLT_PPP
		return nil
	case "FDDI":
		*t = DLT_FDDI
		return nil
	case "ATM_RFC1483":
		*t = DLT_ATM_RFC1483
		return nil
	case "RAW":
		*t = DLT_RAW
		return nil
	case "SLIP_BSDOS":
		*t = DLT_SLIP_BSDOS
		return nil
	case "PPP_BSDOS":
		*t = DLT_PPP_BSDOS
		return nil
	case "ATM_CLIP":
		*t = DLT_ATM_CLIP
		return nil
	case "REDBACK_SMARTEDGE":
		*t = DLT_REDBACK_SMARTEDGE
		return nil
	case "PPP_SERIAL":
		*t = DLT_PPP_SERIAL
		return nil
	case "PPP_ETHER":
		*t = DLT_PPP_ETHER
		return nil
	case "SYMANTEC_FIREWALL":
		*t = DLT_SYMANTEC_FIREWALL
		return nil
	case "C_HDLC":
		*t = DLT_C_HDLC
		return nil
	case "IEEE802_11":
		*t = DLT_IEEE802_11
		return nil
	case "FRELAY":
		*t = DLT_FRELAY
		return nil
	case "LOOP":
		*t = DLT_LOOP
		return nil
	case "ENC":
		*t = DLT_ENC
		return nil
	case "HDLC":
		*t = DLT_HDLC
		return nil
	case "LINUX_SLL":
		*t = DLT_LINUX_SLL
		return nil
	case "LTALK":
		*t = DLT_LTALK
		return nil
	case "ECONET":
		*t = DLT_ECONET
		return nil
	case "IPFILTER":
		*t = DLT_IPFILTER
		return nil
	case "PFLOG":
		*t = DLT_PFLOG
		return nil
	case "CISCO_IOS":
		*t = DLT_CISCO_IOS
		return nil
	case "PRISM_HEADER":
		*t = DLT_PRISM_HEADER
		return nil
	case "AIRONET_HEADER":
		*t = DLT_AIRONET_HEADER
		return nil
	case "HHDLC":
		*t = DLT_HHDLC
		return nil
	case "IP_OVER_FC":
		*t = DLT_IP_OVER_FC
		return nil
	case "SUNATM":
		*t = DLT_SUNATM
		return nil
	case "RIO":
		*t = DLT_RIO
		return nil
	case "PCI_EXP":
		*t = DLT_PCI_EXP
		return nil
	case "AURORA":
		*t = DLT_AURORA
		return nil
	case "IEEE802_11_RADIO":
		*t = DLT_IEEE802_11_RADIO
		return nil
	case "TZSP":
		*t = DLT_TZSP
		return nil
	case "ARCNET_LINUX":
		*t = DLT_ARCNET_LINUX
		return nil
	case "JUNIPER_MLPPP":
		*t = DLT_JUNIPER_MLPPP
		return nil
	case "JUNIPER_MLFR":
		*t = DLT_JUNIPER_MLFR
		return nil
	case "JUNIPER_ES":
		*t = DLT_JUNIPER_ES
		return nil
	case "JUNIPER_GGSN":
		*t = DLT_JUNIPER_GGSN
		return nil
	case "JUNIPER_MFR":
		*t = DLT_JUNIPER_MFR
		return nil
	case "JUNIPER_ATM2":
		*t = DLT_JUNIPER_ATM2
		return nil
	case "JUNIPER_SERVICES":
		*t = DLT_JUNIPER_SERVICES
		return nil
	case "JUNIPER_ATM1":
		*t = DLT_JUNIPER_ATM1
		return nil
	case "APPLE_IP_OVER_IEEE1394":
		*t = DLT_APPLE_IP_OVER_IEEE1394
		return nil
	case "MTP2_WITH_PHDR":
		*t = DLT_MTP2_WITH_PHDR
		return nil
	case "MTP2":
		*t = DLT_MTP2
		return nil
	case "MTP3":
		*t = DLT_MTP3
		return nil
	case "SCCP":
		*t = DLT_SCCP
		return nil
	case "DOCSIS":
		*t = DLT_DOCSIS
		return nil
	case "LINUX_IRDA":
		*t = DLT_LINUX_IRDA
		return nil
	case "IBM_SP":
		*t = DLT_IBM_SP
		return nil
	case "IBM_SN":
		*t = DLT_IBM_SN
		return nil
	case "USER0":
		*t = DLT_USER0
		return nil
	case "USER1":
		*t = DLT_USER1
		return nil
	case "USER2":
		*t = DLT_USER2
		return nil
	case "USER3":
		*t = DLT_USER3
		return nil
	case "USER4":
		*t = DLT_USER4
		return nil
	case "USER5":
		*t = DLT_USER5
		return nil
	case "USER6":
		*t = DLT_USER6
		return nil
	case "USER7":
		*t = DLT_USER7
		return nil
	case "USER8":
		*t = DLT_USER8
		return nil
	case "USER9":
		*t = DLT_USER9
		return nil
	case "USER10":
		*t = DLT_USER10
		return nil
	case "USER11":
		*t = DLT_USER11
		return nil
	case "USER12":
		*t = DLT_USER12
		return nil
	case "USER13":
		*t = DLT_USER13
		return nil
	case "USER14":
		*t = DLT_USER14
		return nil
	case "USER15":
		*t = DLT_USER15
		return nil
	case "IEEE802_11_RADIO_AVS":
		*t = DLT_IEEE802_11_RADIO_AVS
		return nil
	case "JUNIPER_MONITOR":
		*t = DLT_JUNIPER_MONITOR
		return nil
	case "BACNET_MS_TP":
		*t = DLT_BACNET_MS_TP
		return nil
	case "PPP_PPPD":
		*t = DLT_PPP_PPPD
		return nil
	case "JUNIPER_PPPOE":
		*t = DLT_JUNIPER_PPPOE
		return nil
	case "JUNIPER_PPPOE_ATM":
		*t = DLT_JUNIPER_PPPOE_ATM
		return nil
	case "GPRS_LLC":
		*t = DLT_GPRS_LLC
		return nil
	case "GPF_T":
		*t = DLT_GPF_T
		return nil
	case "GPF_F":
		*t = DLT_GPF_F
		return nil
	case "GCOM_T1E1":
		*t = DLT_GCOM_T1E1
		return nil
	case "GCOM_SERIAL":
		*t = DLT_GCOM_SERIAL
		return nil
	case "JUNIPER_PIC_PEER":
		*t = DLT_JUNIPER_PIC_PEER
		return nil
	case "ERF_ETH":
		*t = DLT_ERF_ETH
		return nil
	case "ERF_POS":
		*t = DLT_ERF_POS
		return nil
	case "LINUX_LAPD":
		*t = DLT_LINUX_LAPD
		return nil
	case "JUNIPER_ETHER":
		*t = DLT_JUNIPER_ETHER
		return nil
	case "JUNIPER_PPP":
		*t = DLT_JUNIPER_PPP
		return nil
	case "JUNIPER_FRELAY":
		*t = DLT_JUNIPER_FRELAY
		return nil
	case "JUNIPER_CHDLC":
		*t = DLT_JUNIPER_CHDLC
		return nil
	case "MFR":
		*t = DLT_MFR
		return nil
	case "JUNIPER_VP":
		*t = DLT_JUNIPER_VP
		return nil
	case "A429":
		*t = DLT_A429
		return nil
	case "A653_ICM":
		*t = DLT_A653_ICM
		return nil
	case "USB":
		*t = DLT_USB
		return nil
	case "USB_FREEBSD":
		*t = DLT_USB_FREEBSD
		return nil
	case "BLUETOOTH_HCI_H4":
		*t = DLT_BLUETOOTH_HCI_H4
		return nil
	case "IEEE802_16_MAC_CPS":
		*t = DLT_IEEE802_16_MAC_CPS
		return nil
	case "USB_LINUX":
		*t = DLT_USB_LINUX
		return nil
	case "CAN20B":
		*t = DLT_CAN20B
		return nil
	case "IEEE802_15_4_LINUX":
		*t = DLT_IEEE802_15_4_LINUX
		return nil
	case "PPI":
		*t = DLT_PPI
		return nil
	case "IEEE802_16_MAC_CPS_RADIO":
		*t = DLT_IEEE802_16_MAC_CPS_RADIO
		return nil
	case "JUNIPER_ISM":
		*t = DLT_JUNIPER_ISM
		return nil
	case "IEEE802_15_4_WITHFCS":
		*t = DLT_IEEE802_15_4_WITHFCS
		return nil
	case "SITA":
		*t = DLT_SITA
		return nil
	case "ERF":
		*t = DLT_ERF
		return nil
	case "RAIF1":
		*t = DLT_RAIF1
		return nil
	case "IPMB_KONTRON":
		*t = DLT_IPMB_KONTRON
		return nil
	case "JUNIPER_ST":
		*t = DLT_JUNIPER_ST
		return nil
	case "BLUETOOTH_HCI_H4_WITH_PHDR":
		*t = DLT_BLUETOOTH_HCI_H4_WITH_PHDR
		return nil
	case "AX25_KISS":
		*t = DLT_AX25_KISS
		return nil
	case "LAPD":
		*t = DLT_LAPD
		return nil
	case "PPP_WITH_DIR":
		*t = DLT_PPP_WITH_DIR
		return nil
	case "C_HDLC_WITH_DIR":
		*t = DLT_C_HDLC_WITH_DIR
		return nil
	case "FRELAY_WITH_DIR":
		*t = DLT_FRELAY_WITH_DIR
		return nil
	case "LAPB_WITH_DIR":
		*t = DLT_LAPB_WITH_DIR
		return nil
	case "I2C_LINUX":
		*t = DLT_I2C_LINUX
		return nil
	case "IPMB_LINUX":
		*t = DLT_IPMB_LINUX
		return nil
	case "FLEXRAY":
		*t = DLT_FLEXRAY
		return nil
	case "MOST":
		*t = DLT_MOST
		return nil
	case "LIN":
		*t = DLT_LIN
		return nil
	case "X2E_SERIAL":
		*t = DLT_X2E_SERIAL
		return nil
	case "X2E_XORAYA":
		*t = DLT_X2E_XORAYA
		return nil
	case "IEEE802_15_4_NONASK_PHY":
		*t = DLT_IEEE802_15_4_NONASK_PHY
		return nil
	case "LINUX_EVDEV":
		*t = DLT_LINUX_EVDEV
		return nil
	case "GSMTAP_UM":
		*t = DLT_GSMTAP_UM
		return nil
	case "GSMTAP_ABIS":
		*t = DLT_GSMTAP_ABIS
		return nil
	case "MPLS":
		*t = DLT_MPLS
		return nil
	case "USB_LINUX_MMAPPED":
		*t = DLT_USB_LINUX_MMAPPED
		return nil
	case "DECT":
		*t = DLT_DECT
		return nil
	case "AOS":
		*t = DLT_AOS
		return nil
	case "WIHART":
		*t = DLT_WIHART
		return nil
	case "FC_2":
		*t = DLT_FC_2
		return nil
	case "FC_2_WITH_FRAME_DELIMS":
		*t = DLT_FC_2_WITH_FRAME_DELIMS
		return nil
	case "IPNET":
		*t = DLT_IPNET
		return nil
	case "CAN_SOCKETCAN":
		*t = DLT_CAN_SOCKETCAN
		return nil
	case "IPV4":
		*t = DLT_IPV4
		return nil
	case "IPV6":
		*t = DLT_IPV6
		return nil
	case "IEEE802_15_4_NOFCS":
		*t = DLT_IEEE802_15_4_NOFCS
		return nil
	case "DBUS":
		*t = DLT_DBUS
		return nil
	case "JUNIPER_VS":
		*t = DLT_JUNIPER_VS
		return nil
	case "JUNIPER_SRX_E2E":
		*t = DLT_JUNIPER_SRX_E2E
		return nil
	case "JUNIPER_FIBRECHANNEL":
		*t = DLT_JUNIPER_FIBRECHANNEL
		return nil
	case "DVB_CI":
		*t = DLT_DVB_CI
		return nil
	case "MUX27010":
		*t = DLT_MUX27010
		return nil
	case "STANAG_5066_D_PDU":
		*t = DLT_STANAG_5066_D_PDU
		return nil
	case "JUNIPER_ATM_CEMIC":
		*t = DLT_JUNIPER_ATM_CEMIC
		return nil
	case "NFLOG":
		*t = DLT_NFLOG
		return nil
	case "NETANALYZER":
		*t = DLT_NETANALYZER
		return nil
	case "NETANALYZER_TRANSPARENT":
		*t = DLT_NETANALYZER_TRANSPARENT
		return nil
	case "IPOIB":
		*t = DLT_IPOIB
		return nil
	case "MPEG_2_TS":
		*t = DLT_MPEG_2_TS
		return nil
	case "NG40":
		*t = DLT_NG40
		return nil
	case "NFC_LLCP":
		*t = DLT_NFC_LLCP
		return nil
	case "PFSYNC":
		*t = DLT_PFSYNC
		return nil
	case "INFINIBAND":
		*t = DLT_INFINIBAND
		return nil
	case "SCTP":
		*t = DLT_SCTP
		return nil
	case "USBPCAP":
		*t = DLT_USBPCAP
		return nil
	case "RTAC_SERIAL":
		*t = DLT_RTAC_SERIAL
		return nil
	case "BLUETOOTH_LE_LL":
		*t = DLT_BLUETOOTH_LE_LL
		return nil
	case "WIRESHARK_UPPER_PDU":
		*t = DLT_WIRESHARK_UPPER_PDU
		return nil
	case "NETLINK":
		*t = DLT_NETLINK
		return nil
	case "BLUETOOTH_LINUX_MONITOR":
		*t = DLT_BLUETOOTH_LINUX_MONITOR
		return nil
	case "BLUETOOTH_BREDR_BB":
		*t = DLT_BLUETOOTH_BREDR_BB
		return nil
	case "BLUETOOTH_LE_LL_WITH_PHDR":
		*t = DLT_BLUETOOTH_LE_LL_WITH_PHDR
		return nil
	case "PROFIBUS_DL":
		*t = DLT_PROFIBUS_DL
		return nil
	case "PKTAP":
		*t = DLT_PKTAP
		return nil
	case "EPON":
		*t = DLT_EPON
		return nil
	case "IPMI_HPM_2":
		*t = DLT_IPMI_HPM_2
		return nil
	case "ZWAVE_R1_R2":
		*t = DLT_ZWAVE_R1_R2
		return nil
	case "ZWAVE_R3":
		*t = DLT_ZWAVE_R3
		return nil
	case "WATTSTOPPER_DLM":
		*t = DLT_WATTSTOPPER_DLM
		return nil
	case "ISO_14443":
		*t = DLT_ISO_14443
		return nil
	case "RDS":
		*t = DLT_RDS
		return nil
	case "USB_DARWIN":
		*t = DLT_USB_DARWIN
		return nil
	case "OPENFLOW":
		*t = DLT_OPENFLOW
		return nil
	case "SDLC":
		*t = DLT_SDLC
		return nil
	case "TI_LLN_SNIFFER":
		*t = DLT_TI_LLN_SNIFFER
		return nil
	case "LORATAP":
		*t = DLT_LORATAP
		return nil
	case "VSOCK":
		*t = DLT_VSOCK
		return nil
	case "NORDIC_BLE":
		*t = DLT_NORDIC_BLE
		return nil
	case "DOCSIS31_XRA31":
		*t = DLT_DOCSIS31_XRA31
		return nil
	case "ETHERNET_MPACKET":
		*t = DLT_ETHERNET_MPACKET
		return nil
	case "DISPLAYPORT_AUX":
		*t = DLT_DISPLAYPORT_AUX
		return nil
	case "LINUX_SLL2":
		*t = DLT_LINUX_SLL2
		return nil
	case "SERCOS_MONITOR":
		*t = DLT_SERCOS_MONITOR
		return nil
	case "OPENVIZSLA":
		*t = DLT_OPENVIZSLA
		return nil
	case "EBHSCR":
		*t = DLT_EBHSCR
		return nil
	case "VPP_DISPATCH":
		*t = DLT_VPP_DISPATCH
		return nil
	case "DSA_TAG_BRCM":
		*t = DLT_DSA_TAG_BRCM
		return nil
	case "DSA_TAG_BRCM_PREPEND":
		*t = DLT_DSA_TAG_BRCM_PREPEND
		return nil
	case "IEEE802_15_4_TAP":
		*t = DLT_IEEE802_15_4_TAP
		return nil
	case "DSA_TAG_DSA":
		*t = DLT_DSA_TAG_DSA
		return nil
	case "DSA_TAG_EDSA":
		*t = DLT_DSA_TAG_EDSA
		return nil
	case "ELEE":
		*t = DLT_ELEE
		return nil
	case "Z_WAVE_SERIAL":
		*t = DLT_Z_WAVE_SERIAL
		return nil
	case "USB_2_0":
		*t = DLT_USB_2_0
		return nil
	case "ATSC_ALP":
		*t = DLT_ATSC_ALP
		return nil
	case "ETW":
		*t = DLT_ETW
		return nil
	case "NETANALYZER_NG":
		*t = DLT_NETANALYZER_NG
		return nil
	case "ZBOSS_NCP":
		*t = DLT_ZBOSS_NCP
		return nil
	case "USB_2_0_LOW_SPEED":
		*t = DLT_USB_2_0_LOW_SPEED
		return nil
	case "USB_2_0_FULL_SPEED":
		*t = DLT_USB_2_0_FULL_SPEED
		return nil
	case "USB_2_0_HIGH_SPEED":
		*t = DLT_USB_2_0_HIGH_SPEED
		return nil
	case "AUERSWALD_LOG":
		*t = DLT_AUERSWALD_LOG
		return nil
	case "ZWAVE_TAP":
		*t = DLT_ZWAVE_TAP
		return nil
	case "SILABS_DEBUG_CHANNEL":
		*t = DLT_SILABS_DEBUG_CHANNEL
		return nil
	case "FIRA_UCI":
		*t = DLT_FIRA_UCI
		return nil
	case "MDB":
		*t = DLT_MDB
		return nil
	case "DECT_NR":
		*t = DLT_DECT_NR
		return nil
	case "EDK2_MM":
		*t = DLT_EDK2_MM
		return nil
	case "DEBUG_ONLY":
		*t = DLT_DEBUG_ONLY
		return nil
	default:
		if n, err := strconv.ParseInt(string(buf), 0, 0); err == nil {
			*t = LinkType(n)
			return nil
		}
		return fmt.Errorf("invalid link type %q", buf)
	}
}
