//go:build ignore

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

var (
	Output = flag.String("o", "const.go", "output path")
)

func main() {
	flag.Parse()

	if err := run(flag.Args()...); err != nil {
		fmt.Fprintf(os.Stderr, "error: generate constants: %v\n", err)
		os.Exit(1)
	}
}

func run(src ...string) error {
	var b strings.Builder
	b.WriteString("// Code generated by constgen; DO NOT EDIT.\n\n")
	b.WriteString("package bpf_wasm\n")
	seen := map[string]bool{}
	for _, name := range src {
		buf, err := os.ReadFile(name)
		if err != nil {
			return err
		}

		type entry struct {
			name string
			val  string
		}
		var entries []entry
		for line := range bytes.Lines(buf) {
			parts := strings.Fields(strings.TrimSpace(string(line)))
			if len(parts) != 3 || parts[0] != "#define" {
				continue
			}

			name := parts[1]
			if seen[name] {
				return fmt.Errorf("duplicate %q", name)
			}
			seen[name] = true

			val := parts[2]
			_, err := strconv.ParseInt(val, 0, 0)
			if err != nil {
				return fmt.Errorf("invalid %q %q: %w", name, val, err)
			}
			entries = append(entries, entry{name, val})
		}

		b.WriteString("\nconst (\n")
		for _, e := range entries {
			fmt.Fprintf(&b, "%s = %s\n", e.name, e.val)
		}
		b.WriteString(")\n")
	}
	if out, err := format.Source([]byte(b.String())); err != nil {
		return fmt.Errorf("format: %w", err)
	} else if err := os.WriteFile(*Output, out, 0644); err != nil {
		return err
	}
	return nil
}
